name: CI Workflow  # Name of the workflow

on:
  push:
  pull_request:

jobs:
  # Job Lint
  lint:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner
    defaults:
      run:
        working-directory: ci_lab  # Set the default working directory for all steps

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # Ensure consistency in Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest
        run: pytest --cov=src --cov-report=term-missing

      - name: Install Flake8
        run: pip install flake8

      - name: Run Flake8 Linting
        run: flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

  # Job test
  test:
    runs-on: ubuntu-latest
    needs: lint 
    defaults:
      run:
        working-directory: ci_lab
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Set Up Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.9"
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
        - name: Run Tests Wtih Pytests
          run: pytest --cov=src --cov-report=term-missing

  # Job coverage
  coverage:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: ci_lab
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install Dependencies
        run: pip install -r requirements.txt
      - name: Check Coverage Threshold
        run: pytest --cov=src --cov-fail-under=80    
